CREATE TABLE CATEGORIES
(
    CATEGORY_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME ENUM (
        'FRUIT',
        'VEGETABLE',
        'DAIRY',
        'MEAT',
        'FISH',
        'BAKERY',
        'BEVERAGE',
        'SNACK',
        'CANNED',
        'CLEANING',
        'PERSONAL_CARE',
        'ELECTRONICS',
        'STATIONERY',
        'CLOTHING',
        'UNDEFINED'
        )
        NOT NULL DEFAULT 'UNDEFINED',
    CATEGORY_DESC TEXT
);

CREATE TABLE PRODUCTS
(
    PRODUCT_ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME         VARCHAR(255)   NOT NULL,
    PRODUCT_DESCRIPTION  TEXT,
    CATEGORY_ID          BIGINT         NOT NULL,
    PRODUCT_PRICE        DECIMAL(15, 2) NOT NULL,
    PRODUCT_MANUFACTURER VARCHAR(255)   NOT NULL,
    PRODUCT_STOCK        INT,
    PRODUCT_MIN_STOCK    INT,
    PRODUCT_MAX_STOCK    INT,
    PRODUCT_ACTIVE       BOOLEAN,
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID)

);