USE audit_labs;
CREATE TABLE AUDIT_PRODUCTS
(
    AUDIT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    OLD_PRODUCT_NAME VARCHAR(255),
    NEW_PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE VARCHAR(255) NOT NULL,
    OPERATION VARCHAR(255) NOT NULL,
    AUDIT_USER VARCHAR(255) NOT NULL,
    AUDIT_DATE TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)