USE audit_labs;

CREATE TABLE AUDIT_PRODUCTS
(
    AUDIT_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID       BIGINT,
    OLD_PRODUCT_NAME VARCHAR(255),
    NEW_PRODUCT_NAME VARCHAR(255),
    OLD_PRODUCT_DESCRIPTION TEXT,
    NEW_PRODUCT_DESCRIPTION TEXT,
    OLD_PRODUCT_PRICE DECIMAL(15, 2),
    NEW_PRODUCT_PRICE DECIMAL(15, 2),
    OLD_PRODUCT_STOCK INT,
    NEW_PRODUCT_STOCK INT,
    OPERATION        VARCHAR(50),
    AUDIT_USER       VARCHAR(255),
    AUDIT_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);