USE audit_labs;

CREATE TABLE USERS
(
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);
CREATE TABLE ROLES
(
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(255) NOT NULL
);
CREATE TABLE USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);